"""added productcategory models that links the products table as well as category table.

Revision ID: bf4e3bd63e81
Revises: e9d04196039e
Create Date: 2021-09-30 09:54:40.790967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4e3bd63e81'
down_revision = 'e9d04196039e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcategory',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoryid'], ['category.categoryid'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.PrimaryKeyConstraint('categoryid', 'productid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productcategory')
    # ### end Alembic commands ###
