"""added orderproduct table and defined.

Revision ID: e54ccb6110fb
Revises: 0e343c394634
Create Date: 2021-09-30 10:39:35.546520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54ccb6110fb'
down_revision = '0e343c394634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderproduct',
    sa.Column('ordproductid', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderid'], ['order.orderid'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.PrimaryKeyConstraint('ordproductid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderproduct')
    # ### end Alembic commands ###
